// Catálogo del "Kit de estrategias para transformar la interacción pedagógica"
// (Fundación Educacional Arauco y Focus). Son las dos familias del cuadernillo:
// 32 estrategias de clima de aula y 75 estrategias de pensamiento.
// Se usa tanto en la pauta de feedback de clase como en el endpoint de IA que
// completa la pauta a partir de un relato hablado.

export type FocusStrategy = { n: number; name: string; purpose: string };

export const CLIMATE_STRATEGIES: FocusStrategy[] = [
  { n: 1, name: "Mano arriba, es silencio", purpose: "Desarrolla la atención plena, la autorregulación emocional y genera un clima propicio para el aprendizaje." },
  { n: 2, name: "Puño en mi pecho", purpose: "Desarrolla la regulación del grupo durante tareas que implican distintos ritmos de solución." },
  { n: 3, name: "Comodín compañero/a", purpose: "Estimula la capacidad de pedir ayuda y la colaboración en el aprendizaje." },
  { n: 4, name: "Saludo emocionante", purpose: "Genera conexión emocional positiva entre NNA y agentes educativos." },
  { n: 5, name: "El camino de la alegría", purpose: "Promueve un clima de disfrute y bienestar en el grupo, favoreciendo la conexión entre NNA." },
  { n: 6, name: "La alfombra roja", purpose: "Fortalece la autoestima, fomenta vínculos positivos y aumenta la energía del grupo." },
  { n: 7, name: "Trazos en el cielo", purpose: "Favorece la comunicación, la atención compartida y la creatividad." },
  { n: 8, name: "Caras y emociones", purpose: "Genera clima de disfrute y cohesión grupal a la vez que fomenta la expresión emocional." },
  { n: 9, name: "Conteo Zen", purpose: "Promueve la atención plena, la colaboración y la cohesión grupal." },
  { n: 10, name: "Atrapa y escapa", purpose: "Promueve la atención compartida, el vínculo positivo, la coordinación y la participación grupal." },
  { n: 11, name: "Blandiblú", purpose: "Promueve la atención compartida, el vínculo positivo, la coordinación y la participación grupal." },
  { n: 12, name: "Pelota y paleta", purpose: "Promueve la atención compartida, el vínculo positivo, la coordinación y la participación grupal." },
  { n: 13, name: "Cambio de asientos", purpose: "Vincula positivamente al grupo y fortalece la empatía y la conexión emocional." },
  { n: 14, name: "La bola que se nutre", purpose: "Promueve el sentido grupal, el vínculo positivo y la atención compartida." },
  { n: 15, name: "Caminata consciente", purpose: "Desarrolla la atención plena, la conciencia corporal y activa la creatividad." },
  { n: 16, name: "Posición de confianza", purpose: "Estimula emociones agradables y aumenta la seguridad y confianza personal." },
  { n: 17, name: "Postura de la silla", purpose: "Favorece la concentración, la regulación emocional y la activación corporal." },
  { n: 18, name: "Postura del árbol", purpose: "Favorece la concentración, la regulación emocional y la activación corporal." },
  { n: 19, name: "Relajación corporal", purpose: "Fomenta la conexión corporal y promueve la regulación emocional y la relajación física." },
  { n: 20, name: "Respira y recorre tu mano", purpose: "Desarrolla atención plena, regulación emocional y conciencia corporal." },
  { n: 21, name: "Respiración del chocolate caliente", purpose: "Desarrolla atención plena, regulación emocional y conciencia corporal." },
  { n: 22, name: "Respiración con el cuerpo", purpose: "Desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 23, name: "Respiración del conejo", purpose: "Desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 24, name: "Respiración 7 y 10", purpose: "Desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 25, name: "Respiración de cortar leña", purpose: "Libera tensión y desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 26, name: "Lluvia de energía", purpose: "Desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 27, name: "El reloj de arena", purpose: "Desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 28, name: "Conectar con los sonidos", purpose: "Desarrolla regulación emocional, atención plena y conciencia del entorno." },
  { n: 29, name: "Refugio personal", purpose: "Desarrolla conexión emocional, regulación emocional y autoconocimiento." },
  { n: 30, name: "Relajación de luz", purpose: "Desarrolla regulación emocional, atención plena y conciencia corporal." },
  { n: 31, name: "Meditación PEC", purpose: "Entrena la atención plena, favorece la regulación emocional y permite analizar situaciones." },
  { n: 32, name: "Meditación: sabiduría en lo alto", purpose: "Desarrolla conexión, expresión y regulación emocional." },
];

export const THINKING_STRATEGIES: FocusStrategy[] = [
  { n: 1, name: "Acuerdos clave", purpose: "Promueve la responsabilidad compartida, el clima emocional positivo y la ciudadanía comprometida." },
  { n: 2, name: "Observar lo invisible", purpose: "Desarrolla el pensamiento crítico y ayuda a comprender la relevancia de las partes que componen un todo." },
  { n: 3, name: "¿Qué te hace decir eso? ¿Qué con esto?", purpose: "Promueve el razonamiento y la argumentación basada en evidencia, y permite comprender alternativas y múltiples perspectivas." },
  { n: 4, name: "Círculo de puntos de vista", purpose: "Desarrolla la empatía, el pensamiento crítico y la identificación de múltiples perspectivas sobre un mismo tema." },
  { n: 5, name: "Conectar-Extender-Desafiar", purpose: "Ayuda a hacer conexiones entre nuevas ideas y conocimientos previos, haciendo visible cómo los nuevos aprendizajes se conectan con ideas preexistentes." },
  { n: 6, name: "Antes pensaba / Ahora pienso", purpose: "Permite consolidar nuevos aprendizajes y hacer evidente los cambios de ideas respecto a un tema o problema." },
  { n: 7, name: "Puente 3-2-1", purpose: "Conecta el pensamiento inicial con el nuevo, haciendo visible la evolución del aprendizaje." },
  { n: 8, name: "Qué sientes / Qué necesitas", purpose: "Desarrolla autoconciencia emocional y vocabulario afectivo, comprendiendo la conexión entre emociones y necesidades." },
  { n: 9, name: "Triángulo PEC", purpose: "Promueve la autoconciencia integral sobre cómo una experiencia impacta en el pensamiento, la emoción y el cuerpo." },
  { n: 10, name: "Yo con yo", purpose: "Permite reflexionar profundamente de forma individual para construir comprensión personal de la temática." },
  { n: 11, name: "Semáforo de la emoción: Paro-Pienso-Actúo", purpose: "Permite entrenar la regulación emocional, evaluar las situaciones y sus alternativas de acción." },
  { n: 12, name: "Qué te celebras / Cuál es tu próximo desafío", purpose: "Ayuda a desarrollar conciencia sobre el proceso de aprendizaje, valorar el progreso y establecer metas de mejora." },
  { n: 13, name: "¿Cómo podrías solucionarlo?", purpose: "Fortalece el pensamiento crítico, la confianza y la búsqueda de soluciones." },
  { n: 14, name: "¿Qué puedes hacer ahora con lo que descubriste?", purpose: "Promueve la metacognición y el sentido de propósito del aprendizaje." },
  { n: 15, name: "¿Qué vas/van a hacer y cuándo?", purpose: "Desarrolla la capacidad de planificación, toma de decisiones y compromiso personal." },
  { n: 16, name: "Gracias a mi error aprendí", purpose: "Ayuda a desarrollar perseverancia y reflexión sobre sus procesos, y resignifica los errores como parte del aprendizaje." },
  { n: 17, name: "Me celebro-Nos celebro", purpose: "Promueve la valoración del proceso de aprendizaje y el sentido de comunidad, y fortalece la autoestima." },
  { n: 18, name: "¿Qué hiciste/hicimos para lograrlo?", purpose: "Promueve la metacognición y el reconocimiento del propio proceso de aprendizaje." },
  { n: 19, name: "Pensar-Hacer parejas-Compartir", purpose: "Desarrolla habilidades de escucha activa, consideración de perspectivas diversas y articulación del pensamiento." },
  { n: 20, name: "Parar-Iniciar-Continuar", purpose: "Desarrolla la capacidad de evaluar las propias acciones y tomar decisiones para mejorar el aprendizaje." },
  { n: 21, name: "El semáforo de la comprensión", purpose: "Evalúa objetivos de aprendizaje, permite reflexionar sobre el nivel de comprensión y entrega información para ajustar el proceso." },
  { n: 22, name: "Historia escondida", purpose: "Promueve la exploración de la complejidad y el pensamiento crítico." },
  { n: 23, name: "Hechos-Emoción-Necesidad-Propuesta", purpose: "Promueve una comunicación empática y asertiva, ayuda a comprender distintos puntos de vista y desarrolla la empatía." },
  { n: 24, name: "Color-Símbolo-Imagen", purpose: "Permite extraer la esencia de las ideas de forma no verbal, sintetizando la comprensión a través de representaciones visuales y simbólicas." },
  { n: 25, name: "Preguntas creativas", purpose: "Desarrolla la capacidad de formular preguntas y promueve la curiosidad, la indagación y la creatividad." },
  { n: 26, name: "Titular", purpose: "Desarrolla la capacidad de sintetizar lo más relevante sobre un tema." },
  { n: 27, name: "Cuaderno del reportero", purpose: "Ayuda a diferenciar hechos objetivos de interpretaciones subjetivas, promoviendo el análisis crítico y el discernimiento riguroso de información." },
  { n: 28, name: "Ver-Pensar-Preguntarse", purpose: "Desarrolla habilidades de observación, indagación y razonamiento con evidencia." },
  { n: 29, name: "X2", purpose: "Entrena la observación profunda y desarrolla la capacidad de ir más allá de lo evidente." },
  { n: 30, name: "Zoom in", purpose: "Desarrolla la capacidad de realizar inferencias, descripciones detalladas y la formulación de preguntas en base a secciones o fragmentos." },
  { n: 31, name: "Sé mi profe", purpose: "Desarrolla autonomía y fortalece la cultura de apoyo mutuo y retroalimentación inmediata entre pares." },
  { n: 32, name: "Entrevista simultánea", purpose: "Fomenta escucha activa, formulación de preguntas y valoración de perspectivas diversas mediante diálogos auténticos." },
  { n: 33, name: "Inventario cooperativo", purpose: "Desarrolla pensamiento divergente, colaboración y visibiliza conocimientos propios y colectivos." },
  { n: 34, name: "Gemelos de", purpose: "Fortalece autonomía y responsabilidad, promoviendo hábitos y apoyo mutuo sostenido." },
  { n: 35, name: "Cabezas juntas numeradas", purpose: "Promueve la responsabilidad individual, la construcción colectiva, la escucha activa y el compromiso con el aprendizaje de otros." },
  { n: 36, name: "Podio cooperativo", purpose: "Desarrolla pensamiento crítico, permite evaluar comprensión y fomenta colaboración y consenso grupal." },
  { n: 37, name: "La lista", purpose: "Promueve procesamiento activo de información y permite verificar comprensión de contenidos esenciales de forma colaborativa." },
  { n: 38, name: "El juego de la elaboración", purpose: "Desarrolla la capacidad de sintetizar y construir sobre ideas de otros, promoviendo escucha activa." },
  { n: 39, name: "Plan de trabajo", purpose: "Desarrolla planificación estratégica, promueve autonomía grupal y fomenta responsabilidad individual, facilitando el monitoreo del proceso." },
  { n: 40, name: "Correcciones cooperativas de tareas", purpose: "Promueve el aprendizaje, fomenta el compromiso cognitivo, desarrolla la argumentación y permite identificar dificultades y aciertos comunes." },
  { n: 41, name: "Lápices al centro", purpose: "Asegura comprensión compartida antes del trabajo individual, promoviendo regulación emocional y respeto de turnos." },
  { n: 42, name: "Control grupal", purpose: "Reduce la ansiedad ante evaluaciones y permite detectar dificultades antes de evaluar." },
  { n: 43, name: "Folio giratorio", purpose: "Permite construir respuestas progresivamente, visibilizando la evolución del pensamiento y desarrollando la capacidad de complementar ideas." },
  { n: 44, name: "Aligerar el ambiente", purpose: "Combina desarrollo del pensamiento crítico con motivación y disfrute, generando un ambiente positivo de aprendizaje." },
  { n: 45, name: "Controversia académica", purpose: "Desarrolla pensamiento crítico, argumentación y debate respetuoso, fomentando la capacidad de considerar múltiples perspectivas." },
  { n: 46, name: "Exploración en cuatro sentidos", purpose: "Fomenta la creatividad en la expresión de ideas y permite evaluar comprensión de conceptos mediante su capacidad de relacionarlos." },
  { n: 47, name: "Tomo una y doy una", purpose: "Promueve el intercambio activo de ideas, desarrolla la escucha activa y fomenta conversaciones significativas." },
  { n: 48, name: "Rutina de la X", purpose: "Permite explorar un concepto desde diferentes perspectivas, enriqueciendo la comprensión y desarrollando pensamiento creativo." },
  { n: 49, name: "Círculo de las preocupaciones", purpose: "Contribuye a regular la ansiedad y el estrés, desarrollando sentido de agencia y protagonismo sobre la propia vida." },
  { n: 50, name: "Describe como cámara de video", purpose: "Promueve una comunicación basada en hechos observables, en lugar de juicios o interpretaciones." },
  { n: 51, name: "Inicios de preguntas", purpose: "Desarrolla la capacidad de formular buenas preguntas, aumentando la curiosidad y las habilidades de reflexión, conexión e indagación." },
  { n: 52, name: "Vaso medio lleno / Vaso medio vacío", purpose: "Promueve la mentalidad de crecimiento y la conciencia sobre cómo las interpretaciones afectan emociones, motivación y resultados." },
  { n: 53, name: "Gracias con sentido", purpose: "Desarrolla la capacidad de expresar agradecimiento significativo, fortaleciendo relaciones y clima de aula." },
  { n: 54, name: "Afirmar-Apoyar-Preguntar", purpose: "Promueve razonamiento crítico, interpretaciones fundamentadas en evidencia y cuestionamiento reflexivo de las propias ideas." },
  { n: 55, name: "Perspectivas del conflicto", purpose: "Promueve la resolución de conflictos mediante toma de perspectiva, reconociendo las emociones y necesidades." },
  { n: 56, name: "¿Verdad para quién?", purpose: "Fomenta el pensamiento crítico y la comprensión de la realidad desde múltiples perspectivas." },
  { n: 57, name: "Conversación sobre papel", purpose: "Fomenta comprensión colaborativa permitiendo que todos opinen sin interrupciones y asegurando participación equitativa." },
  { n: 58, name: "Comparaciones creativas", purpose: "Promueve comprensión profunda mediante comparaciones metafóricas entre tópicos nuevos y temáticas conocidas." },
  { n: 59, name: "Café mundial", purpose: "Permite explorar y elaborar ideas de manera colaborativa, haciendo visible el pensamiento de todos y asegurando que sea escuchado y valorado." },
  { n: 60, name: "Momento ¡Ahá!", purpose: "Contribuye a desarrollar la capacidad metacognitiva de reconocer cuándo una experiencia o aprendizaje puede ser transferido a otras situaciones." },
  { n: 61, name: "Artefacto de la comprensión", purpose: "Fomenta metacognición, comprensión creativa y pensamiento simbólico, traduciendo ideas complejas en representaciones tangibles." },
  { n: 62, name: "Estrategia del ascensor", purpose: "Desarrolla la capacidad de sintetizar, organizar ideas según relevancia y evaluar la profundidad de la propia comprensión." },
  { n: 63, name: "Generar-Ordenar-Conectar-Elaborar", purpose: "Permite organizar ideas sobre un tema y construir comprensión profunda mediante el descubrimiento de conexiones significativas entre conceptos." },
  { n: 64, name: "Uno-Dos-Cuatro", purpose: "Genera participación individual y colaborativa, promoviendo compromiso cognitivo, escucha activa y construcción progresiva de ideas." },
  { n: 65, name: "Parejas de escritura y edición cooperativa", purpose: "Desarrolla el proceso de escritura completo, fomentando retroalimentación entre pares y reflexión sobre cómo mejorar las propias ideas." },
  { n: 66, name: "Cuerda de la verdad", purpose: "Desarrolla el pensamiento crítico, el razonamiento basado en evidencia y la apertura a múltiples perspectivas." },
  { n: 67, name: "Pelar la fruta", purpose: "Estructura el pensamiento en diferentes niveles de profundidad y desarrolla la metacognición." },
  { n: 68, name: "Mapa de la definición", purpose: "Permite visualizar la estructura completa de un concepto, facilitando su comprensión y memorización significativa." },
  { n: 69, name: "Mapa web", purpose: "Facilita la visualización y organización de ideas, explicitando las conexiones entre ellas." },
  { n: 70, name: "Diagrama de Venn", purpose: "Desarrolla pensamiento analítico al comparar y contrastar dos o más conceptos, ideas u objetos." },
  { n: 71, name: "Mapa causa y efecto", purpose: "Desarrolla razonamiento lógico, capacidad de explicación y comprensión de cadenas causales complejas." },
  { n: 72, name: "Árbol de problemas", purpose: "Desarrolla el pensamiento crítico analizando problemas complejos y promoviendo el análisis profundo antes de proponer soluciones." },
  { n: 73, name: "Lista de cotejo", purpose: "Fomenta autonomía y reduce ansiedad mediante expectativas explícitas." },
  { n: 74, name: "Rúbrica", purpose: "Permite autoevaluación y coevaluación formativa, orientando el esfuerzo hacia aspectos específicos que mejorar." },
  { n: 75, name: "Pauta de observación", purpose: "Desarrolla capacidad de observación sistemática de procesos, conductas y presentaciones." },
];

export const CLIMATE_STRATEGY_NAMES = CLIMATE_STRATEGIES.map((item) => item.name);
export const THINKING_STRATEGY_NAMES = THINKING_STRATEGIES.map((item) => item.name);
