export type EmotionColor = "Rojo" | "Azul" | "Amarillo" | "Verde";

export type LevelId =
  | "prebasica"
  | "primero-segundo"
  | "tercero-cuarto"
  | "segundo-ciclo"
  | "tercer-ciclo";

export type RevoltijoCard = {
  id: string;
  level: LevelId;
  color: EmotionColor;
  activityType: string;
  prompt: string;
  support: string;
  strength: string;
  nextColor: EmotionColor;
};

export const levelOptions: Array<{ id: LevelId; label: string; shortLabel: string }> = [
  { id: "prebasica", label: "Prebásica", shortLabel: "Prebásica" },
  { id: "primero-segundo", label: "1° y 2° básico", shortLabel: "1°-2°" },
  { id: "tercero-cuarto", label: "3° y 4° básico", shortLabel: "3°-4°" },
  { id: "segundo-ciclo", label: "Segundo ciclo, 11 a 15 años", shortLabel: "11-15" },
  { id: "tercer-ciclo", label: "Tercer ciclo, 14 a 19 años", shortLabel: "14-19" },
];

export const colorMeanings: Record<EmotionColor, string> = {
  Rojo: "activación, enojo, miedo, frustración",
  Azul: "tristeza, desmotivación, soledad",
  Amarillo: "energía, entusiasmo, motivación",
  Verde: "calma, gratitud, regulación, bienestar",
};

export const colorStyles: Record<EmotionColor, { bg: string; text: string; ring: string; soft: string }> = {
  Rojo: {
    bg: "bg-red-500",
    text: "text-red-700",
    ring: "ring-red-200",
    soft: "bg-red-50",
  },
  Azul: {
    bg: "bg-sky-500",
    text: "text-sky-700",
    ring: "ring-sky-200",
    soft: "bg-sky-50",
  },
  Amarillo: {
    bg: "bg-amber-400",
    text: "text-amber-700",
    ring: "ring-amber-200",
    soft: "bg-amber-50",
  },
  Verde: {
    bg: "bg-emerald-500",
    text: "text-emerald-700",
    ring: "ring-emerald-200",
    soft: "bg-emerald-50",
  },
};

export const revoltijoCards: RevoltijoCard[] = [
  {
    id: "pre-rojo-1",
    level: "prebasica",
    color: "Rojo",
    activityType: "Movimiento",
    prompt: "Haz cara de volcán enojado y luego derrite el volcán con tres soplos lentos.",
    support: "El cuerpo baja la intensidad cuando respira despacio.",
    strength: "Tengo afán de superación",
    nextColor: "Verde",
  },
  {
    id: "pre-rojo-2",
    level: "prebasica",
    color: "Rojo",
    activityType: "Imaginación",
    prompt: "Imagina un botón de pausa. ¿Dónde lo pondrías en tu cuerpo cuando te frustras?",
    support: "Pausar ayuda a elegir mejor.",
    strength: "Hago las cosas bien",
    nextColor: "Azul",
  },
  {
    id: "pre-azul-1",
    level: "prebasica",
    color: "Azul",
    activityType: "Conversación",
    prompt: "Nombra algo pequeño que te acompañe cuando estás triste.",
    support: "Recordar compañía abriga por dentro.",
    strength: "Soy amable",
    nextColor: "Amarillo",
  },
  {
    id: "pre-azul-2",
    level: "prebasica",
    color: "Azul",
    activityType: "Juego oral",
    prompt: "Completa: Hoy mi corazón está como un clima de...",
    support: "Poner nombre al clima emocional ayuda.",
    strength: "Soy respetuoso",
    nextColor: "Verde",
  },
  {
    id: "pre-amarillo-1",
    level: "prebasica",
    color: "Amarillo",
    activityType: "Movimiento",
    prompt: "Haz una pose de superenergía y di una cosa que quieras intentar.",
    support: "La energía también puede servir para aprender.",
    strength: "Soy entusiasta",
    nextColor: "Rojo",
  },
  {
    id: "pre-amarillo-2",
    level: "prebasica",
    color: "Amarillo",
    activityType: "Pregunta",
    prompt: "¿Qué juego te da ganas de compartir con alguien?",
    support: "Compartir entusiasmo une al grupo.",
    strength: "Soy constructivo",
    nextColor: "Verde",
  },
  {
    id: "pre-verde-1",
    level: "prebasica",
    color: "Verde",
    activityType: "Respiración",
    prompt: "Respira como si olieras una flor y soplaras una pluma, tres veces.",
    support: "La respiración suave ordena el cuerpo.",
    strength: "Tengo propósito",
    nextColor: "Amarillo",
  },
  {
    id: "pre-verde-2",
    level: "prebasica",
    color: "Verde",
    activityType: "Gratitud",
    prompt: "Di gracias con una palabra, un gesto o una sonrisa.",
    support: "Agradecer hace crecer el bienestar.",
    strength: "Soy amable",
    nextColor: "Rojo",
  },
  {
    id: "12-rojo-1",
    level: "primero-segundo",
    color: "Rojo",
    activityType: "Movimiento",
    prompt: "Aprieta tus manos como piedra, suelta como nube. Repite tres veces.",
    support: "Soltar tensión ayuda a pensar mejor.",
    strength: "Hago las cosas bien",
    nextColor: "Verde",
  },
  {
    id: "12-rojo-2",
    level: "primero-segundo",
    color: "Rojo",
    activityType: "Pregunta",
    prompt: "¿Qué frase respetuosa puedes usar cuando algo te molesta?",
    support: "Decirlo con respeto cuida el vínculo.",
    strength: "Soy respetuoso",
    nextColor: "Azul",
  },
  {
    id: "12-azul-1",
    level: "primero-segundo",
    color: "Azul",
    activityType: "Conversación",
    prompt: "Cuenta una forma de pedir compañía sin interrumpir a otros.",
    support: "Pedir ayuda también es valentía.",
    strength: "Soy amable",
    nextColor: "Amarillo",
  },
  {
    id: "12-azul-2",
    level: "primero-segundo",
    color: "Azul",
    activityType: "Imaginación",
    prompt: "Si tu tristeza fuera una mochila, ¿qué podrías sacar para que pese menos?",
    support: "Imaginar permite ordenar lo que sentimos.",
    strength: "Tengo afán de superación",
    nextColor: "Verde",
  },
  {
    id: "12-amarillo-1",
    level: "primero-segundo",
    color: "Amarillo",
    activityType: "Juego oral",
    prompt: "Di una idea para hacer más alegre el recreo de alguien.",
    support: "La alegría compartida construye curso.",
    strength: "Soy constructivo",
    nextColor: "Verde",
  },
  {
    id: "12-amarillo-2",
    level: "primero-segundo",
    color: "Amarillo",
    activityType: "Movimiento",
    prompt: "Haz una mini celebración silenciosa por algo que aprendiste.",
    support: "Celebrar avances motiva a seguir.",
    strength: "Soy entusiasta",
    nextColor: "Rojo",
  },
  {
    id: "12-verde-1",
    level: "primero-segundo",
    color: "Verde",
    activityType: "Respiración",
    prompt: "Cuenta hasta cuatro al inhalar y hasta cuatro al exhalar.",
    support: "Contar le da ritmo a la calma.",
    strength: "Tengo propósito",
    nextColor: "Amarillo",
  },
  {
    id: "12-verde-2",
    level: "primero-segundo",
    color: "Verde",
    activityType: "Reflexión",
    prompt: "Nombra una cosa buena que pasó hoy, aunque haya sido pequeña.",
    support: "Mirar lo bueno fortalece el bienestar.",
    strength: "Soy amable",
    nextColor: "Rojo",
  },
  {
    id: "34-rojo-1",
    level: "tercero-cuarto",
    color: "Rojo",
    activityType: "Reflexión",
    prompt: "Cuando te frustras, ¿qué señal te da tu cuerpo primero?",
    support: "Detectar señales tempranas evita explotar.",
    strength: "Tengo afán de superación",
    nextColor: "Verde",
  },
  {
    id: "34-rojo-2",
    level: "tercero-cuarto",
    color: "Rojo",
    activityType: "Juego oral",
    prompt: "Di una respuesta firme y respetuosa para un momento injusto.",
    support: "Firme no significa agresivo.",
    strength: "Soy respetuoso",
    nextColor: "Azul",
  },
  {
    id: "34-azul-1",
    level: "tercero-cuarto",
    color: "Azul",
    activityType: "Conversación",
    prompt: "¿Qué puede hacer un compañero para ayudarte cuando estás apagado?",
    support: "Explicar lo que sirve facilita el apoyo.",
    strength: "Soy amable",
    nextColor: "Amarillo",
  },
  {
    id: "34-azul-2",
    level: "tercero-cuarto",
    color: "Azul",
    activityType: "Imaginación",
    prompt: "Inventa un nombre para un lugar seguro en tu mente.",
    support: "Un lugar mental seguro ayuda a regularse.",
    strength: "Tengo propósito",
    nextColor: "Verde",
  },
  {
    id: "34-amarillo-1",
    level: "tercero-cuarto",
    color: "Amarillo",
    activityType: "Pregunta",
    prompt: "¿Qué meta pequeña te entusiasma para esta semana?",
    support: "Las metas pequeñas mueven grandes cambios.",
    strength: "Soy entusiasta",
    nextColor: "Verde",
  },
  {
    id: "34-amarillo-2",
    level: "tercero-cuarto",
    color: "Amarillo",
    activityType: "Movimiento",
    prompt: "Haz con tus manos una señal de equipo y explica qué significa.",
    support: "Los gestos pueden unir al curso.",
    strength: "Soy constructivo",
    nextColor: "Rojo",
  },
  {
    id: "34-verde-1",
    level: "tercero-cuarto",
    color: "Verde",
    activityType: "Respiración",
    prompt: "Respira lento y piensa: entro calma, sale tensión.",
    support: "Una frase breve guía la atención.",
    strength: "Hago las cosas bien",
    nextColor: "Amarillo",
  },
  {
    id: "34-verde-2",
    level: "tercero-cuarto",
    color: "Verde",
    activityType: "Gratitud",
    prompt: "Agradece en voz alta una acción buena que viste en el curso.",
    support: "Reconocer lo bueno lo vuelve más visible.",
    strength: "Soy amable",
    nextColor: "Rojo",
  },
  {
    id: "sc-rojo-1",
    level: "segundo-ciclo",
    color: "Rojo",
    activityType: "Reflexión",
    prompt: "Piensa en una reacción impulsiva común. ¿Qué pausa de 10 segundos podría cambiarla?",
    support: "Una pausa breve abre opciones.",
    strength: "Hago las cosas bien",
    nextColor: "Verde",
  },
  {
    id: "sc-rojo-2",
    level: "segundo-ciclo",
    color: "Rojo",
    activityType: "Conversación",
    prompt: "¿Cómo expresarías molestia sin atacar la identidad de otra persona?",
    support: "Criticar conductas cuida la dignidad.",
    strength: "Soy respetuoso",
    nextColor: "Azul",
  },
  {
    id: "sc-azul-1",
    level: "segundo-ciclo",
    color: "Azul",
    activityType: "Pregunta",
    prompt: "Cuando alguien se aísla, ¿qué acercamiento puede sentirse respetuoso?",
    support: "Acompañar también puede ser dar espacio.",
    strength: "Soy amable",
    nextColor: "Amarillo",
  },
  {
    id: "sc-azul-2",
    level: "segundo-ciclo",
    color: "Azul",
    activityType: "Reflexión",
    prompt: "Nombra una idea que te quita ánimo y una frase más justa para reemplazarla.",
    support: "Revisar pensamientos cambia el peso emocional.",
    strength: "Tengo afán de superación",
    nextColor: "Verde",
  },
  {
    id: "sc-amarillo-1",
    level: "segundo-ciclo",
    color: "Amarillo",
    activityType: "Juego oral",
    prompt: "En una frase, invita al curso a una acción positiva para hoy.",
    support: "La motivación necesita dirección.",
    strength: "Tengo propósito",
    nextColor: "Verde",
  },
  {
    id: "sc-amarillo-2",
    level: "segundo-ciclo",
    color: "Amarillo",
    activityType: "Movimiento",
    prompt: "Haz una postura de confianza y di qué responsabilidad puedes asumir.",
    support: "La energía se vuelve valiosa cuando construye.",
    strength: "Soy constructivo",
    nextColor: "Rojo",
  },
  {
    id: "sc-verde-1",
    level: "segundo-ciclo",
    color: "Verde",
    activityType: "Respiración",
    prompt: "Inhala 4, sostén 2, exhala 6. Nota qué cambia en tu cuerpo.",
    support: "Exhalar más largo suele bajar activación.",
    strength: "Hago las cosas bien",
    nextColor: "Amarillo",
  },
  {
    id: "sc-verde-2",
    level: "segundo-ciclo",
    color: "Verde",
    activityType: "Gratitud",
    prompt: "Menciona una conducta del curso que ayuda a sentirse seguro.",
    support: "Nombrar prácticas sanas las protege.",
    strength: "Soy respetuoso",
    nextColor: "Rojo",
  },
  {
    id: "tc-rojo-1",
    level: "tercer-ciclo",
    color: "Rojo",
    activityType: "Reflexión",
    prompt: "Identifica una frontera personal que necesitas comunicar mejor.",
    support: "Los límites claros reducen conflictos repetidos.",
    strength: "Soy respetuoso",
    nextColor: "Verde",
  },
  {
    id: "tc-rojo-2",
    level: "tercer-ciclo",
    color: "Rojo",
    activityType: "Conversación",
    prompt: "¿Qué diferencia hay entre reaccionar desde el orgullo y responder desde tus valores?",
    support: "Responder desde valores da dirección.",
    strength: "Tengo propósito",
    nextColor: "Azul",
  },
  {
    id: "tc-azul-1",
    level: "tercer-ciclo",
    color: "Azul",
    activityType: "Pregunta",
    prompt: "¿Qué tipo de apoyo pedirías si te sintieras desconectado por varios días?",
    support: "Pedir apoyo temprano es autocuidado.",
    strength: "Tengo afán de superación",
    nextColor: "Amarillo",
  },
  {
    id: "tc-azul-2",
    level: "tercer-ciclo",
    color: "Azul",
    activityType: "Imaginación",
    prompt: "Imagina que aconsejas a un amigo en tu misma emoción. ¿Qué le dirías sin juzgar?",
    support: "La autocompasión también se entrena.",
    strength: "Soy amable",
    nextColor: "Verde",
  },
  {
    id: "tc-amarillo-1",
    level: "tercer-ciclo",
    color: "Amarillo",
    activityType: "Reflexión",
    prompt: "Nombra una motivación que venga de ti y no de la presión externa.",
    support: "La motivación propia sostiene procesos largos.",
    strength: "Tengo propósito",
    nextColor: "Verde",
  },
  {
    id: "tc-amarillo-2",
    level: "tercer-ciclo",
    color: "Amarillo",
    activityType: "Juego oral",
    prompt: "Crea una frase breve para activar al grupo sin competir ni burlarse.",
    support: "El entusiasmo sano incluye a otros.",
    strength: "Soy entusiasta",
    nextColor: "Rojo",
  },
  {
    id: "tc-verde-1",
    level: "tercer-ciclo",
    color: "Verde",
    activityType: "Respiración",
    prompt: "Haz tres respiraciones lentas y elige una palabra para volver al presente.",
    support: "Una palabra ancla ayuda bajo presión.",
    strength: "Hago las cosas bien",
    nextColor: "Amarillo",
  },
  {
    id: "tc-verde-2",
    level: "tercer-ciclo",
    color: "Verde",
    activityType: "Gratitud",
    prompt: "Reconoce una acción silenciosa que mejora la convivencia del curso.",
    support: "Lo que se reconoce se puede repetir.",
    strength: "Soy constructivo",
    nextColor: "Rojo",
  },
];
